project:
  type: website
  output-dir: docs

website:
  title: "CDT Conference"
  navbar:
    title: Conference 2026<span class='icon-line'></span>
    right:
      - href: index.qmd#sec-about
        text: About
      - href: index.qmd#sec-cfa
        text: Call for Abstracts
      - href: index.qmd#sec-keynotes
        text: Keynotes
      - href: index.qmd#sec-agenda
        text: Agenda
      - href: index.qmd#sec-venue
        text: Venue
      - href: index.qmd#sec-organisers
        text: Organisers
      - href: index.qmd#sec-contact
        text: Contact Us
      - text: Past Editions
        menu:
          - text: "2025"
            href: https://ai-medical-cdt.github.io/conference2025/
            target: _blank
          - text: "2024"
            href: https://sites.google.com/view/leedsaimedicalcdtconference?usp=sharing
            target: _blank
  page-footer:  
    left: >-
     Made with <a href="https://quarto.org" style="font-weight:bold" target="_blank">Quarto</a>
    center: |
      <a class="cdt-link" href="https://ai-medical.leeds.ac.uk/" title="CDT Website" target="_blank" rel="noopener">{{< fa globe size=xl >}}</a>
      <a class="cdt-link" href="https://x.com/LeedsMedAI_CDT" title="CDT Twitter" target="_blank" rel="noopener">{{< fa brands twitter size=xl >}}</a>
      <a class="cdt-link" href="https://leeds-ai-cdt.github.io/" title="CDT Blog" target="_blank" rel="noopener">{{< fa blog size=xl >}}</a>
    right: |
      ![](assets/imgs/logos.png){fig-alt="logos" width=280px}
  back-to-top-navigation: true

format:
  html:
    toc: false
    theme: 
      light: [cosmo, assets/styles/light_theme.scss, assets/styles/agenda_style.scss]
      dark: [cosmo, assets/styles/dark_theme.scss, assets/styles/agenda_style.scss]
    css: assets/styles/styles.css
    smooth-scroll: true
    code-link: true
    pagetitle: "{{< meta title >}}"
    lightbox: true
